site_name: Drakes
theme: readthedocs 
repo_url: https://github.com/shakna-israel/drakes
site_description: Genius doesn't come easy. 
site_author: shakna-israel 
use_directory_urls: true 
pages:
 - [index.md, Home]
 - [LICENSE.md, License]
 - [CONTRIBUTING.md, Contributing]
 - [Drakes.md, Drakes]
